name: Minyan Dafna
markdown: redcarpet
pygments: true
meta:
  site_title: "Minyan Dafna"
  site_subtitle: "A new independent minyan in Berkeley"
  site_language: "en"
permalink: pretty
bower: bower_components/
timezone: America/Los_Angeles