---
title: Minyan Dafna
timezone: America/Los_Angeles
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  events:
    title: Events
    output: true
name: Minyan Dafna
meta:
  site_title: Minyan Dafna
  site_subtitle: Berkeley Independent Minyan
  site_language: en
permalink: pretty
markdown: kramdown
bower: bower_components/
sass:
  sass_dir: _sass
future: 1
